### ISSUE TITLE
Timeboxed, How do we enable component intra-integrations on databricks

### ISSUE THREAD

**Issue by KPeen** [Energinet-DataHub/MightyDucks#23]

**Comment by djorgensendk** [comment]
This was a timeboxed activity, and that timebox has now ended.

**Conslusions**
- I haven't been able to find any existing use cases, examples, or tutorials describing how to conduct what we call intra-domain integration tests on Databricks as part of the CI pipeline.

- I did see examples of integration tests, where jobs were sent to an existing Databricks workspace already deployed in Azure. The DB workspace was however not created or destroyed as part of the CI pipeline.

- Due to my lack of previous experience with Spark, Databricks, and containerization I wan't able to come up a design for how to implement a viable solution to enable intra-integration tests of the Databricks logic.

**How to proceed from here**
- On Monday, when the DevSession 2.0 begins I will propose this as a topic up for discussion, so that people from other teams can be engaged.

**Comment by djorgensendk** [comment]
@Sondergaard can you please review the conclusions I wrote on this issue?

**Comment by Sondergaard** [comment]
I agree with above conclusion
